### PR TITLE
fixed no body errors in debug endpoints

### LINKED ISSUE #513: create rule endpoint returns 500 error when body is empty
```bash
curl -v -X POST http://localhost:8080/api/insights-results-aggregator/v1/rules/some.python.module
```
Current behaviour:
```
< HTTP/1.1 500 Internal Server Error
{"status":"Internal Server Error"}
```
Expected behaviour: 400 error with some message

### LINKED ISSUE #514: create rule_error_key endpoint returns 500 error when body is empty
```bash
curl -v -X POST http://localhost:8080/api/insights-results-aggregator/v1/rules/some.python.module/error_keys/ek
```
Current behaviour:
```
< HTTP/1.1 500 Internal Server Error
{"status":"Internal Server Error"}
```
Expected behaviour: 400 error with some message

### PR DESCRIPTION
**Pull request by Sergey1011010**
# Description

Fixes #513
Fixes #514

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update
- Unit tests (no changes in the code)

## Testing steps

`make before_commit`

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -295,6 +295,9 @@ func (server *HTTPServer) createRule(writer http.ResponseWriter, request *http.R
 
 	err = json.NewDecoder(request.Body).Decode(&rule)
 	if err != nil {
+		if err.Error() == "EOF" {
```
Comment (tisnik) [inline server/server.go:298]: is not it better to use constant?

File: server/errors.go [hunk 2]
```diff
@@ -60,23 +60,26 @@ func (e *AuthenticationError) Error() string {
...
 
 	var respErr error
 
 	switch err := err.(type) {
-	case *RouterMissingParamError:
-		respErr = responses.SendError(writer, err.Error())
-	case *RouterParsingError:
-		respErr = responses.SendError(writer, err.Error())
+	case *RouterMissingParamError, *RouterParsingError, *json.SyntaxError, *NoBodyError:
+		respErr = responses.Send(http.StatusBadRequest, writer, err.Error())
```
Comment (Bee-lee) [inline server/errors.go:78]: Can you pls use the `SendError()` so that its unified? `Send()` is currently only used here and I will rename it in `utils` next sprint to `SendBadRequest()`

File: server/server.go (hunk 1 above)
Comment (Sergey1011010) [reply server/server.go:298]: good idea, thanks

File: server/errors.go (hunk 2 above)
Comment (Sergey1011010) [reply server/errors.go:78]: The reason why I didn't use SendError() is that it's not really clear from the name of the function what kind of error it's gonna send. 

> I will rename it in utils next sprint to SendBadRequest()

Okay, thanks
