### PR TITLE
Fixed minor issues in check-coverage.sh script

### LINKED ISSUE #122: Issues in a script check-coverage.sh
The following minor issues has been found in check-coverage.sh script:

```
In ./check_coverage.sh line 24:
if (( $(echo $go_tool_cover_output | grep -i total | awk '{print $NF}' | egrep "^[-0-9]+" -o) > $THRESHOLD )); then
             ^-- SC2086: Double quote to prevent globbing and word splitting.
                                                                         ^-- SC2196: egrep is non-standard and deprecated. Use grep -E instead.
                                                                                                ^-- SC2004: $/${} is unnecessary on arithmetic variables.


In ./check_coverage.sh line 27:
    echo -e "\033[31m$ERR_MESSAGE\e[0m"
             ^-- SC1117: Backslash is literal in "\0". Prefer explicit escaping: "\\0".
                                 ^-- SC1117: Backslash is literal in "\e". Prefer explicit escaping: "\\e".

```

### PR DESCRIPTION
**Pull request by tisnik**
# Description

Fixed issues in check-coverage.sh

Fixes #122

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Testing steps
Just use this script (as done on CI already)

### CODE REVIEW

File: check_coverage.sh [hunk 1]
```diff
@@ -21,9 +21,9 @@ go_tool_cover_output=$(go tool cover -func=coverage.out)
 
 echo "$go_tool_cover_output"
 
-if (( $(echo $go_tool_cover_output | grep -i total | awk '{print $NF}' | egrep "^[-0-9]+" -o) > $THRESHOLD )); then
+if (( $(echo "$go_tool_cover_output" | grep -i total | awk '{print $NF}' | grep -E "^[-0-9]+" -o) > THRESHOLD )); then
```
Comment (Sergey1011010) [inline check_coverage.sh]: also this `"^[-0-9]+"` should be `"^[0-9]+"`

Comment (tisnik) [reply check_coverage.sh]: Yeh, -55% is not proper coverage :)
