### PR TITLE
Fixed issue #262

### LINKED ISSUE #262: Bunch of string constants detected in storage package
Bunch of string constants detected in `storage` package:

```
storage/storage.go:133:7:1 other occurrence(s) of "sqlite3" found in: storage/sql_hooks.go:86:17
storage/sql_hooks.go:86:17:1 other occurrence(s) of "sqlite3" found in: storage/storage.go:133:7
storage/storage.go:118:37:2 other occurrence(s) of "postgres" found in: storage/storage.go:135:7 storage/sql_hooks.go:88:7
storage/storage.go:135:7:2 other occurrence(s) of "postgres" found in: storage/storage.go:118:37 storage/sql_hooks.go:88:7
storage/sql_hooks.go:88:7:2 other occurrence(s) of "postgres" found in: storage/storage.go:118:37 storage/storage.go:135:7
storage/storage.go:116:37:1 other occurrence(s) of "sqlite" found in: storage/sql_hooks.go:86:7
storage/sql_hooks.go:86:7:1 other occurrence(s) of "sqlite" found in: storage/storage.go:116:37
storage/storage.go:204:16:1 other occurrence(s) of "error" found in: storage/storage.go:227:16
storage/storage.go:227:16:1 other occurrence(s) of "error" found in: storage/storage.go:204:16
```

### PR DESCRIPTION
**Pull request by tisnik**
# Description

Fixes #262

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Testing steps
N/A

### CODE REVIEW

File: storage/sql_hooks.go [hunk 1]
```diff
@@ -83,9 +83,9 @@ func InitAndGetSQLDriverWithLogs(driverName string, logger *log.Logger) (string,
 	var driver sql_driver.Driver
 
 	switch driverName {
-	case "sqlite", "sqlite3":
+	case "sqlite", sqliteDriverName:
```
Comment (Sergey1011010) [inline storage/sql_hooks.go]: maybe it's better to remove "sqlite" here?

Comment (tisnik) [reply storage/sql_hooks.go]: should it happen that "sqlite" will be set?

Comment (Sergey1011010) [reply storage/sql_hooks.go]: so far we use sqlite3 in configs
