### PR TITLE
Fix error 258

### LINKED ISSUE #258: Repeated string 'driver %v is not supported' that can be written as constant found in storage module
```
storage/sql_hooks.go:91:25:2 other occurrence(s) of "driver %v is not supported" found in: storage/storage.go:117:26 storage/storage.go:143:24
storage/storage.go:117:26:2 other occurrence(s) of "driver %v is not supported" found in: storage/sql_hooks.go:91:25 storage/storage.go:143:24
storage/storage.go:143:24:2 other occurrence(s) of "driver %v is not supported" found in: storage/sql_hooks.go:91:25 storage/storage.go:117:26
```

### PR DESCRIPTION
**Pull request by tisnik**
# Description

Fixes #258

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Testing steps
N/A

### CODE REVIEW

File: storage/sql_hooks_test.go [hunk 1]
```diff
@@ -51,7 +51,7 @@ func TestInitAndGetSQLDriverWithLogsDriverNotFound(t *testing.T) {
 	logger := log.New(os.Stdout, "[sql]", log.LstdFlags)
 	const nonExistingDriver = "asdfaserxcvzasfd"
 	_, err := storage.InitAndGetSQLDriverWithLogs(nonExistingDriver, logger)
-	if err == nil || err.Error() != fmt.Sprintf("driver %v is not supported", nonExistingDriver) {
+	if err == nil || err.Error() != fmt.Sprintf("driver '%v' is not supported", nonExistingDriver) {
```
Comment (JoseLSegura) [inline storage/sql_hooks_test.go]: You are not using the `const` here. Maybe different package?

Comment (tisnik) [reply storage/sql_hooks_test.go]: yes, it is in tests
