### PR TITLE
Fix in script check_coverage.sh

### LINKED ISSUE #689: Don't use hardcoded terminal colors in `check_coverage.sh`
Currently, hardcoded terminal colors are used in `check_coverage.sh`. It would be better to use tput command instead. Additionaly prob. OK/Fail message will be more visible by using background colors.

### PR DESCRIPTION
**Pull request by tisnik**
# Description

Fixes #689 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: check_coverage.sh [hunk 1]
```diff
@@ -15,9 +15,10 @@
 
 
 THRESHOLD=85
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-NC='\033[0m' # No Color
+
+RED_BG=$(tput setab 1)
+GREEN_BG=$(tput setab 2)
+NC=$(tput sgr0) # No Color
```
Comment (JoseLSegura) [inline check_coverage.sh:21]: I haven't seen this way to define the colors. Nice to learn :-D
