### PR TITLE
Fixed strange ci error

### LINKED ISSUE #737: Possible bug or strange message on CI during testing
```
Exiting and killing all children...

./test.sh: line 37:  5025 Terminated              INSIGHTS_RESULTS_AGGREGATOR__LOGGING__LOG_LEVEL=$LOG_LEVEL INSIGHTS_RESULTS_AGGREGATOR_CONFIG_FILE=./tests/tests ./insights-results-aggregator || echo -e "${COLORS_RED}service exited with error${COLORS_RESET}"

The command "make integration_tests" exited with 0.
```

### PR DESCRIPTION
**Pull request by Sergey1011010**
# Description

Increasing timeout to let processes stop normally.

Fixes #737

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Testing steps

`make before_commit`

### CODE REVIEW

File: test.sh [hunk 1]
```diff
@@ -38,14 +38,22 @@ function cleanup() {
...
-            # wait for it to stop correctly
-            sleep 10
-            kill -9 "$pid" &>/dev/null
+            # we even gave them plenty of time to think
+            sleep 2
         fi
     done
+
+    for pid in $(print_descendent_pids $$); do
+        # murdering those who're alive
```
Comment (quarckster) [inline test.sh:53]: kill'em all 😈

Comment (tisnik) [reply test.sh:53]: indeed :)
