### PR TITLE
Fixing Makefile to execute shellcheck over the whole Bash base code

### LINKED ISSUE #715: Shellcheck is not being executed for all Bash scripts
I just realized that `shellcheck` rule in `Makefile` only run the checks for `local_storage/populate_db_with_mock_data.sh` and `utils/fill_in_results.sh`.

In fact, it is hiding some shell warnings in several scripts in the root directory

### PR DESCRIPTION
**Pull request by JoseLSegura**
# Description

The current `make shellcheck` execution only checks a minimal subset of our Bash scripts. It is needed to run it over the whole Bash codebase.

Fixes #715

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- Refactor (refactoring code, removing useless files)

## Testing steps

CI

### CODE REVIEW

File: gosec.sh [hunk 1]
```diff
@@ -20,11 +20,6 @@ NC=$(tput sgr0) # No Color
 
 GO_SEC_ARGS=""
 
-VERBOSE=false
-if [[ $* == *verbose* ]]; then
-    VERBOSE=true
-fi
-
```
Comment (JoseLSegura) [inline gosec.sh:27]: Shellcheck reported that `VERBOSE` is not used, but I don't know if `go sec` use it behind the scenes. Could you confirm?

File: test.sh [hunk 2]
```diff
@@ -95,8 +95,9 @@ function test_rest_api() {
     # Without this, the DB could be locked because
     # the migrations have not yet finished.
     sleep 2
-    for i in {1..5}; do
-        populate_db_with_mock_data 2>/dev/null && break || sleep 1
+    for _ in {1..5}; do
+        populate_db_with_mock_data 2>/dev/null && break
+        sleep 1
```
Comment (JoseLSegura) [inline test.sh:100]: I guess that the meaning of both versions is equivalent, but the previous one reported [`SC2015: Note that A && B || C is not if-then-else. C may run when A is true.`](https://www.shellcheck.net/wiki/SC2015)

File: unit-tests.sh [hunk 3]
```diff
@@ -15,11 +15,12 @@
 
 
 CONFIG_FILE=config-devel.toml
-POSTGRES_PORT=$(cat $CONFIG_FILE | grep -i pg_port | grep -E -o '[0-9]+')
+POSTGRES_PORT=$(grep -i pg_port $CONFIG_FILE | grep -E -o '[0-9]+')
 
 function run_unit_tests() {
-    go test -coverprofile coverage.out $(go list ./... | grep -v tests)
-    if [ $? -ne 0 ]; then
+    # shellcheck disable=SC2046
```
Comment (JoseLSegura) [inline unit-tests.sh:21]: I was totally unable to resolve this problem without breaking tests execution, so I disabled this warning

File: Makefile [hunk 4]
```diff
@@ -31,7 +31,7 @@ ineffassign: ## Run ineffassign checker
 	./ineffassign.sh
 
 shellcheck: ## Run shellcheck
-	shellcheck **/*.sh
+	shellcheck *.sh */*.sh
```
Comment (Sergey1011010) [inline Makefile:34]: Probably `find . -exec` would also work here

File: gosec.sh (hunk 1 above)
Comment (Sergey1011010) [reply gosec.sh:27]: the next `if` was supposed to be not the same as this one, but to check `VERBOSE` variable

File: Makefile (hunk 4 above)
Comment (JoseLSegura) [reply Makefile:34]: Maybe, but we can have Python scripts that are executable too, so I prefer to find them using the extension (probably using `find . -name "*.sh"` could be better...
